package cs310.creativeteamname.server;

import java.util.HashMap;
/**
 * This class is an embarrassing display of Dan's poor decision making skills.
 * Please do not look at the source code of this class.
 * @author Dan
 *
 */
public class TemporaryImageHack {
	private HashMap<Integer, String> imgMap = new HashMap<Integer, String>();
	{
		initializeMap();
	}
	public String getImage(int id){
		return imgMap.get(id);
	}
	public void initializeMap(){
		imgMap.put(1, "value)/parks/parks/images/arbutusvillage03.jpg");
		imgMap.put(2, "/parks/parks/images/carnarvon03.jpg");
		imgMap.put(3, "/parks/parks/images/princeofwales03.jpg");
		imgMap.put(4, "/parks/parks/images/pugetparksite01.jpg");
		imgMap.put(5, "/parks/parks/images/quesnelparksite01.jpg");
		imgMap.put(6, "/parks/parks/images/quilchena03.jpg");
		imgMap.put(7, "/parks/parks/images/ravine02.jpg");
		imgMap.put(8, "/parks/parks/images/trafalgar03.jpg");
		imgMap.put(9, "/parks/parks/images/trafalgarmini01.jpg");
		imgMap.put(10, "/parks/parks/images/andylivingstone03.jpg");
		imgMap.put(11, "/parks/parks/images/cardero03.jpg");
		imgMap.put(12, "/parks/parks/images/cathedral02.jpg");
		imgMap.put(13, "/parks/parks/images/coalharbour04.jpg");
		imgMap.put(14, "/parks/parks/images/coopers03.jpg");
		imgMap.put(15, "/parks/parks/images/creekside03.jpg");
		imgMap.put(16, "/parks/parks/images/davidlam04.jpg");
		imgMap.put(17, "/parks/parks/images/devonian04.jpg");
		imgMap.put(18, "/parks/parks/images/discovery04.jpg");
		imgMap.put(19, "/parks/parks/images/emerybarnes02.jpg");
		imgMap.put(20, "/parks/parks/images/harbourgreen02.jpg");
		imgMap.put(21, "/parks/parks/images/helmcken04.jpg");
		imgMap.put(22, "/parks/parks/images/marina03.jpg");
		imgMap.put(23, "/parks/parks/images/maylornebrown03.jpg");
		imgMap.put(24, "/parks/parks/images/pioneer02.jpg");
		imgMap.put(25, "/parks/parks/images/portal03.jpg");
		imgMap.put(26, "/parks/parks/images/crab04.jpg");
		imgMap.put(27, "/parks/parks/images/roundhouse04.jpg");
		imgMap.put(28, "/parks/parks/images/sunyatsen05.jpg");
		imgMap.put(29, "/parks/parks/images/victory04.jpg");
		imgMap.put(30, "/parks/parks/images/wendypoole02.jpg");
		imgMap.put(31, "/parks/parks/images/balaclava03.jpg");
		imgMap.put(32, "/parks/parks/images/blenheimparksite02.jpg");
		imgMap.put(33, "/parks/parks/images/chaldecott03.jpg");
		imgMap.put(34, "/parks/parks/images/deeringisland03.jpg");
		imgMap.put(35, "/parks/parks/images/memorialwest04.jpg");
		imgMap.put(36, "/parks/parks/images/musqueam04.jpg");
		imgMap.put(37, "/parks/parks/images/quadra01.jpg");
		imgMap.put(38, "/parks/parks/images/valdez02.jpg");
		imgMap.put(39, "/parks/parks/images/charleson04.jpg");
		imgMap.put(40, "/parks/parks/images/granville02.jpg");
		imgMap.put(41, "/parks/parks/images/granvilleloop04.jpg");
		imgMap.put(42, "/parks/parks/images/sutcliffe04.jpg");
		imgMap.put(43, "/parks/parks/images/willow02.jpg");
		imgMap.put(44, "/parks/parks/images/alicetownley02.jpg");
		imgMap.put(45, "/parks/parks/images/cambridge03.jpg");
		imgMap.put(46, "/parks/parks/images/garden02.jpg");
		imgMap.put(47, "/parks/parks/images/grandview02.jpg");
		imgMap.put(48, "/parks/parks/images/mcgill03.jpg");
		imgMap.put(49, "/parks/parks/images/mcspadden03.jpg");
		imgMap.put(50, "/parks/parks/images/mosaiccreek03.jpg");
		imgMap.put(51, "/parks/parks/images/oxford02.jpg");
		imgMap.put(52, "/parks/parks/images/pandora02.jpg");
		imgMap.put(53, "/parks/parks/images/salsbury02.jpg");
		imgMap.put(54, "/parks/parks/images/templeton03.jpg");
		imgMap.put(55, "/parks/parks/images/trinityparksite01.jpg");
		imgMap.put(56, "/parks/parks/images/victoria04.jpg");
		imgMap.put(57, "/parks/parks/images/wcshelley02.jpg");
		imgMap.put(58, "/parks/parks/images/woodland03.jpg");
		imgMap.put(59, "/parks/parks/images/adanac03.jpg");
		imgMap.put(60, "/parks/parks/images/bates02.jpg");
		imgMap.put(61, "/parks/parks/images/burrardview04.jpg");
		imgMap.put(62, "/parks/parks/images/callister03.jpg");
		imgMap.put(63, "/parks/parks/images/charles02.jpg");
		imgMap.put(64, "/parks/parks/images/clinton02.jpg");
		imgMap.put(65, "/parks/parks/images/dustygreenwell03.jpg");
		imgMap.put(66, "/parks/parks/images/hastings09.jpg");
		for(int i = 67; i < 245; i++){
			imgMap.put(i, "/parks/parks/images/hastingscommunity03.jpg");
		}
//		imgMap.put(x, "/parks/parks/images/hastingscommunity03.jpg");
//		imgMap.put(x, "/parks/parks/images/kaslo02.jpg");
//		imgMap.put(x, "/parks/parks/images/newbrighton03.jpg");
//		imgMap.put(x, "/parks/parks/images/rupert02.jpg");
//		imgMap.put(x, "/parks/parks/images/sunrise03.jpg");
//		imgMap.put(x, "/parks/parks/images/thunderbird03.jpg");
//		imgMap.put(x, "/parks/parks/images/brewers02.jpg");
//		imgMap.put(x, "/parks/parks/images/cedarcottage01.jpg");
//		imgMap.put(x, "/parks/parks/images/clark03.jpg");
//		imgMap.put(x, "/parks/parks/images/generalbrock03.jpg");
//		imgMap.put(x, "/parks/parks/images/glen02.jpg");
//		imgMap.put(x, "/parks/parks/images/grays03.jpg");
//		imgMap.put(x, "/parks/parks/images/johnhendry03.jpg");
//		imgMap.put(x, "/parks/parks/images/jones03.jpg");
//		imgMap.put(x, "/parks/parks/images/kensington04.jpg");
//		imgMap.put(x, "/parks/parks/images/kingcrest03.jpg");
//		imgMap.put(x, "/parks/parks/images/sunnyside02.jpg");
//		imgMap.put(x, "/parks/parks/images/arbutus02.jpg");
//		imgMap.put(x, "/parks/parks/images/elm03.jpg");
//		imgMap.put(x, "/parks/parks/images/fraserriver07.jpg");
//		imgMap.put(x, "/parks/parks/images/kerrisdalecentennial03.jpg");
//		imgMap.put(x, "/parks/parks/images/malkin02.jpg");
//		imgMap.put(x, "/parks/parks/images/maplegrove03.jpg");
//		imgMap.put(x, "/parks/parks/images/mccleery02.jpg");
//		imgMap.put(x, "/parks/parks/images/mccleerygolf03.jpg");
//		imgMap.put(x, "/parks/parks/images/captaincook02.jpg");
//		imgMap.put(x, "/parks/parks/images/champlain03.jpg");
//		imgMap.put(x, "/parks/parks/images/everett_crowley03.jpg");
//		imgMap.put(x, "/parks/parks/images/fraserview_golf03.jpg");
//		imgMap.put(x, "/parks/parks/images/killarney03.jpg");
//		imgMap.put(x, "/parks/parks/images/kinross01.jpg");
//		imgMap.put(x, "/parks/parks/images/sparwood03.jpg");
//		imgMap.put(x, "/parks/parks/images/almond04.jpg");
//		imgMap.put(x, "/parks/parks/images/connaught03.jpg");
//		imgMap.put(x, "/parks/parks/images/delamont03.jpg");
//		imgMap.put(x, "/parks/parks/images/hadden04.jpg");
//		imgMap.put(x, "/parks/parks/images/jeanbeaty02.jpg");
//		imgMap.put(x, "/parks/parks/images/kitsilano05.jpg");
//		imgMap.put(x, "/parks/parks/images/margaretpigott02.jpg");
//		imgMap.put(x, "/parks/parks/images/mcbride03.jpg");
//		imgMap.put(x, "/parks/parks/images/pointgreytrutch02.jpg");
//		imgMap.put(x, "/parks/parks/images/pointgreystephens02.jpg");
//		imgMap.put(x, "/parks/parks/images/trafalgarparksite02.jpg");
//		imgMap.put(x, "/parks/parks/images/seaforth03.jpg");
//		imgMap.put(x, "/parks/parks/images/tatlow03.jpg");
//		imgMap.put(x, "/parks/parks/images/vanier04.jpg");
//		imgMap.put(x, "/parks/parks/images/volunteer03.jpg");
//		imgMap.put(x, "/parks/parks/images/ash02.jpg");
//		imgMap.put(x, "/parks/parks/images/eburne02.jpg");
//		imgMap.put(x, "/parks/parks/images/marpole02.jpg");
//		imgMap.put(x, "/parks/parks/images/oak04.jpg");
//		imgMap.put(x, "/parks/parks/images/riverview02.jpg");
//		imgMap.put(x, "/parks/parks/images/shannon02.jpg");
//		imgMap.put(x, "/parks/parks/images/williammackie02.jpg");
//		imgMap.put(x, "/parks/parks/images/winona03.jpg");
//		imgMap.put(x, "/parks/parks/images/chinacreeknorth02.jpg");
//		imgMap.put(x, "/parks/parks/images/chinacreeksouth02.jpg");
//		imgMap.put(x, "/parks/parks/images/guelph02.jpg");
//		imgMap.put(x, "/parks/parks/images/jonathanrogers04.jpg");
//		imgMap.put(x, "/parks/parks/images/majormatthews03.jpg");
//		imgMap.put(x, "/parks/parks/images/mountpleasant02.jpg");
//		imgMap.put(x, "/parks/parks/images/robson02.jpg");
//		imgMap.put(x, "/parks/parks/images/teaswamp03.jpg");
//		imgMap.put(x, "/parks/parks/images/cambie02.jpg");
//		imgMap.put(x, "/parks/parks/images/columbia02.jpg");
//		imgMap.put(x, "/parks/parks/images/langaragolf03.jpg");
//		imgMap.put(x, "/parks/parks/images/montgomery03.jpg");
//		imgMap.put(x, "/parks/parks/images/tisdall04.jpg");
//		imgMap.put(x, "/parks/parks/images/beaconsfield02.jpg");
//		imgMap.put(x, "/parks/parks/images/cariboo02.jpg");
//		imgMap.put(x, "/parks/parks/images/carleton02.jpg");
//		imgMap.put(x, "/parks/parks/images/collingwood03.jpg");
//		imgMap.put(x, "/parks/parks/images/earles02.jpg");
//		imgMap.put(x, "/parks/parks/images/falaise05.jpg");
//		imgMap.put(x, "/parks/parks/images/foster01.jpg");
//		imgMap.put(x, "/parks/parks/images/gaston03.jpg");
//		imgMap.put(x, "/parks/parks/images/melbourne02.jpg");
//		imgMap.put(x, "/parks/parks/images/norquay02.jpg");
//		imgMap.put(x, "/parks/parks/images/price01.jpg");
//		imgMap.put(x, "/parks/parks/images/renfrew03.jpg");
//		imgMap.put(x, "/parks/parks/images/renfrewravine02.jpg");
//		imgMap.put(x, "/parks/parks/images/slocan03.jpg");
//		imgMap.put(x, "/parks/parks/images/cartier03.jpg");
//		imgMap.put(x, "/parks/parks/images/grimmett02.jpg");
//		imgMap.put(x, "/parks/parks/images/hillcrest03.jpg");
//		imgMap.put(x, "/parks/parks/images/natbailey01.jpg");
//		imgMap.put(x, "/parks/parks/images/princeedward02.jpg");
//		imgMap.put(x, "/parks/parks/images/queenelizabeth03.JPG");
//		imgMap.put(x, "/parks/parks/images/riley03.jpg");
//		imgMap.put(x, "/parks/parks/images/angus02.jpg");
//		imgMap.put(x, "/parks/parks/images/devonshire02.jpg");
//		imgMap.put(x, "/parks/parks/images/kerrisdale02.jpg");
//		imgMap.put(x, "/parks/parks/images/shaughnessy02.jpg");
//		imgMap.put(x, "/parks/parks/images/vandusen02.JPG");
//		imgMap.put(x, "/parks/parks/images/braemar02.jpg");
//		imgMap.put(x, "/parks/parks/images/douglas03.jpg");
//		imgMap.put(x, "/parks/parks/images/heather02.jpg");
//		imgMap.put(x, "/parks/parks/images/maclean02.jpg");
//		imgMap.put(x, "/parks/parks/images/oppenheimer04.jpg");
//		imgMap.put(x, "/parks/parks/images/strathcona04.jpg");
//		imgMap.put(x, "/parks/parks/images/strathlinear03.jpg");
//		imgMap.put(x, "/parks/parks/images/thornton03.jpg");
//		imgMap.put(x, "/parks/parks/images/george03.jpg");
//		imgMap.put(x, "/parks/parks/images/macdonald03.jpg");
//		imgMap.put(x, "/parks/parks/images/memorialsouth08.jpg");
//		imgMap.put(x, "/parks/parks/images/moberly03.jpg");
//		imgMap.put(x, "/parks/parks/images/ross03.jpg");
//		imgMap.put(x, "/parks/parks/images/sunset03.jpg");
//		imgMap.put(x, "/parks/parks/images/bobolink02.jpg");
//		imgMap.put(x, "/parks/parks/images/fraserview02.jpg");
//		imgMap.put(x, "/parks/parks/images/gladstone02.jpg");
//		imgMap.put(x, "/parks/parks/images/gordon03.jpg");
//		imgMap.put(x, "/parks/parks/images/humm02.jpg");
//		imgMap.put(x, "/parks/parks/images/nanaimo03.jpg");
//		imgMap.put(x, "/parks/parks/images/riverfront04.jpg");
//		imgMap.put(x, "/parks/parks/images/tecumseh04.jpg");
//		imgMap.put(x, "/parks/parks/images/alexandra04.jpg");
//		imgMap.put(x, "/parks/parks/images/barclay04.jpg");
//		imgMap.put(x, "/parks/parks/images/englishbaybeach04.jpg");
//		imgMap.put(x, "/parks/parks/images/morton02.jpg");
//		imgMap.put(x, "/parks/parks/images/nelson02.jpg");
//		imgMap.put(x, "/parks/parks/images/rosemont02.jpg");
//		imgMap.put(x, "/parks/parks/images/stanley04.jpg");
//		imgMap.put(x, "/parks/parks/images/sunsetbeach04.jpg");
//		imgMap.put(x, "/parks/parks/images/rosemarybrown03.jpg");
//		imgMap.put(x, "/parks/parks/images/langara01.jpg");
//		imgMap.put(x, "/parks/parks/images/sahalli03.jpg");
//		imgMap.put(x, "/parks/parks/images/shaughnsesyparksite03.jpg");
//		imgMap.put(x, "/parks/parks/images/hastingsmill02.jpg");
//		imgMap.put(x, "/parks/parks/images/jerichobeach04.jpg");
//		imgMap.put(x, "/parks/parks/images/locarno03.jpg");
//		imgMap.put(x, "/parks/parks/images/spanishbank03.jpg");
//		imgMap.put(x, "/parks/parks/images/westpointgrey03.jpg");
//		imgMap.put(x, "/parks/parks/images/westmount02.jpg");
//		imgMap.put(x, "/parks/parks/images/choklit03.jpg");
//		imgMap.put(x, "/parks/parks/images/georgewainborn04.jpg");
//		imgMap.put(x, "/parks/parks/images/oakmeadow06.jpg");
//		imgMap.put(x, "/parks/parks/images/arbutusgreenway04.jpg");
//		imgMap.put(x, "/parks/parks/images/aberdeen03.jpg");
//		imgMap.put(x, "/parks/parks/images/ebisu07.jpg");
//		imgMap.put(x, "/parks/parks/images/Yaletown04.jpg");
//		imgMap.put(x, "/parks/parks/images/carolina01.jpg");
//		imgMap.put(x, "/parks/parks/images/hinge03.jpg");
//		imgMap.put(x, "/parks/parks/images/habitatisland02.jpg");
//		imgMap.put(x, "/parks/parks/images/fraserrivertrail03.jpg");

	}
}
